### ISSUE TITLE
Improving obstacles generation

### ISSUE THREAD

**Issue by minhVoDuc** [phucvien2511/dodge-game#1]
Việc sinh gai nên chia theo các mức độ khác nhau, tùy thuộc vào số vàng player đang có.
Ý tưởng: 
- Lấy player làm trung tâm, tập trung vùng ô vuông SQR xung quanh player (area nên theo % area của map hoặc tính theo số ô player có thể di chuyển từ lúc có cảnh báo đến khi gai xuất hiện ~ khoảng thời gian T)
- Với các mốc vàng tăng dần thì có thể kết hợp giữa việc tăng lượng gai trong SQR hoặc giảm khoảng thời gian T

**Comment by phucvien2511** [comment]
Chào Minh, cảm ơn bạn đã đóng góp ý kiến cho project của mình. Về 2 thắc mắc trên, mình xin được hồi đáp như sau:
1. Về việc sinh chướng ngại vật (CNV) dựa vào vị trí player: Từ đầu, ý tưởng của trò chơi là để luyện phản xạ và né tránh, do vậy việc tập trung CNV quanh vị trí player có thể khiến họ dễ dàng hơn trong việc phán đoán, từ đó làm giảm đi sự bất ngờ và thú vị của trò chơi. Vì vậy mình vẫn sẽ giữ cơ chế sinh CNV ngẫu nhiên hiện tại.
2. Về việc tăng số CNV dựa trên số coin: Mình đã ghi nhận và điều chỉnh lại thành các mức với độ khó tăng dần dựa trên số điểm.
Cảm ơn Minh vì những ý kiến đóng góp trên!

**Comment by phucvien2511** [comment]
> Việc sinh gai nên chia theo các mức độ khác nhau, tùy thuộc vào số vàng player đang có. Ý tưởng:
> 
> * Lấy player làm trung tâm, tập trung vùng ô vuông SQR xung quanh player (area nên theo % area của map hoặc tính theo số ô player có thể di chuyển từ lúc có cảnh báo đến khi gai xuất hiện ~ khoảng thời gian T)
> * Với các mốc vàng tăng dần thì có thể kết hợp giữa việc tăng lượng gai trong SQR hoặc giảm khoảng thời gian T

Chào Minh, cảm ơn bạn đã đóng góp ý kiến cho project của mình. Về 2 thắc mắc trên, mình xin được hồi đáp như sau:

1. Về việc sinh chướng ngại vật (CNV) dựa vào vị trí player: Từ đầu, ý tưởng của trò chơi là để luyện phản xạ và né tránh, do vậy việc tập trung CNV quanh vị trí player có thể khiến họ dễ dàng hơn trong việc phán đoán, từ đó làm giảm đi sự bất ngờ và thú vị của trò chơi. Vì vậy mình vẫn sẽ giữ cơ chế sinh CNV ngẫu nhiên hiện tại.
2. Về việc tăng số CNV dựa trên số coin: Mình đã ghi nhận và điều chỉnh lại thành các mức với độ khó tăng dần dựa trên số điểm.
Cảm ơn Minh vì những ý kiến đóng góp trên!
